### ISSUE TITLE
Read: weekly test DBS 1

### ISSUE THREAD

**Issue by immkavin-ranks** [immkavin-ranks/life#4]
[Major components of DBMS](https://www.javatpoint.com/components-of-dbms)
[Three level architecture](https://www.javatpoint.com/dbms-three-schema-architecture)
[Client/Server architecture part 1](https://www.javatpoint.com/2-tier-architecture-in-dbms) and 
[Client/Server architecture part 2](https://www.javatpoint.com/centralized-and-client-server-architecture-for-dbms)

**Comment by immkavin-ranks** [comment]
Hi Suresh 👋🏼

**Comment by ikavvii** [comment]
postponed to 05 January 2024

**Comment by ikavvii** [comment]
Wrote not so great 😃
