### ISSUE TITLE
Design and analysis of algorithms NPTEL

### ISSUE THREAD

**Issue by ikavvii** [immkavin-ranks/life#40]

**Comment by immkavin-ranks** [comment]
### Week 1 Quiz

1. An image processing application begins with two n×n matrices A and B. The first phase of preprocessing the inputs takes O(n2) steps for each of A and B. The second step involves a convolution of A and B to yield a new matrix C in time O(n3). This is followed by an edge detection phase that takes times O(n2) for matrix C. What is the most accurate and concise description of the complexity of the overall algorithm?
 O(n2)
 O(n3)
 O(n2+n3)
 O(n5)

> * The overall complexity of the algorithm can be described as O(n^3), where "n" represents the size of the matrices A, B, and C. This is because the dominant term in the overall complexity arises from the convolution step, which takes O(n^3) time. The preprocessing steps for matrices A and B, as well as the edge detection phase for matrix C, contribute to the overall complexity, but they are overshadowed by the convolution step when considering larger input sizes. Therefore, the overall complexity is primarily determined by the convolution operation, resulting in O(n^3).

**Comment by ikavvii** [comment]
Week 1 Quiz 
https://chat.openai.com/share/fe243d67-fcd3-493e-b39b-f04dc4be894f

**Comment by ikavvii** [comment]
Discontinued! And i will plan to join on next semester

**Comment by ikavvii** [comment]
Discontinued! And i will plan to join on next semester
