### ISSUE TITLE
Install oracle in linux

### ISSUE THREAD

**Issue by immkavin-ranks** [immkavin-ranks/life#7]

**Comment by ikavvii** [comment]
Trying once again to install it 

[How to Set Up Oracle Database with Docker](https://www.youtube.com/watch?v=OTglm9fVCL4)

**Comment by ikavvii** [comment]
https://hub.docker.com/r/gvenzl/oracle-xe

**Comment by ikavvii** [comment]
Installing oracle database xe on linux was terrible experience.

**Comment by ikavvii** [comment]
Again not working
